name: scRNA-tme
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - scanpy
  - anndata
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - leidenalg
  - igraph
  - louvain
  - pip
